#!/usr/bin/env sh

limelight -m config width            6
limelight -m config radius           8
limelight -m config placement        exterior
limelight -m config active_color     0xfffc4103
limelight -m config normal_color     0x007d78c4

echo "limelight configuration loaded.."
